# NumPy Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Create a NumPy array containing 10, 20, 30, 40, 50.

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


Q2. Create numbers from 1 to 20.

In [5]:
import numpy as np

arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q3. Create even numbers from 2 to 20.

In [8]:
import numpy as np

e1 = np.arange(2, 21, 2)
print(e1)

[ 2  4  6  8 10 12 14 16 18 20]


Q4. Create a 3×4 matrix of zeros.

In [9]:
import numpy as np

z1 = np.zeros((3, 4))
print(z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q5. Create a 4×3 matrix of ones.

In [10]:
import numpy as np

o1 = np.ones((4, 3))
print(o1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Q6. Generate 10 evenly spaced values between 0 and 1.

In [11]:
import numpy as np

l1 = np.linspace(0, 1, 10)
print(l1)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q7. Create a 2×3 array and find shape, ndim and dtype.

In [12]:
import numpy as np

a1 = np.array([[1, 2, 3],
               [4, 5, 6]])

print(a1)
print("Shape:", a1.shape)
print("Dimensions:", a1.ndim)
print("Datatype:", a1.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Datatype: int64


Q8. Create a 4×5 array and find shape, size and ndim.

In [13]:
import numpy as np

a2 = np.arange(1, 21).reshape(4, 5)

print(a2)
print("Shape:", a2.shape)
print("Size:", a2.size)
print("Dimensions:", a2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)
Size: 20
Dimensions: 2


Q9. Convert [1,2,3,4,5] to float datatype.

In [14]:
import numpy as np

f1 = np.array([1, 2, 3, 4, 5], dtype=float)
print(f1)
print(f1.dtype)

[1. 2. 3. 4. 5.]
float64


Q10. Create numbers 1–12 and reshape into 3×4, 2×6 and 4×3.

In [15]:
import numpy as np

r1 = np.arange(1, 13)

print(r1.reshape(3, 4))
print()

print(r1.reshape(2, 6))
print()

print(r1.reshape(4, 3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q11. Create np.arange(20) and reshape into 4×5 and 5×4.

In [16]:
import numpy as np

r2 = np.arange(20)

print(r2.reshape(4, 5))
print()

print(r2.reshape(5, 4))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Q12. Explain why np.arange(10).reshape(3,4) produces an error.

In [17]:
import numpy as np

x1 = np.arange(10)

# This will produce an error because 10 elements
# cannot be reshaped into a (3,4) array, which requires 12 elements.

# print(x1.reshape(3, 4))

print("Error: 10 elements cannot be reshaped into a 3x4 matrix because 3x4 = 12 elements are required.")

Error: 10 elements cannot be reshaped into a 3x4 matrix because 3x4 = 12 elements are required.


Q13. Using a 4×4 array, extract the first element.

In [18]:
import numpy as np

a3 = np.arange(1, 17).reshape(4, 4)

print(a3)
print("First element:", a3[0, 0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First element: 1


Q14. Extract the value 10 from a 4×4 array created using arange.

In [19]:
import numpy as np

a4 = np.arange(1, 17).reshape(4, 4)

print(a4)
print("Value:", a4[2, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Value: 10


Q15. Extract the last element.

In [20]:
import numpy as np

a5 = np.arange(1, 17).reshape(4, 4)

print(a5)
print("Last element:", a5[-1, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Last element: 16


Q16. Extract the first row.

In [21]:
import numpy as np

a6 = np.arange(1, 17).reshape(4, 4)

print(a6)
print("First row:", a6[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]


Q17. Extract the third row.

In [22]:
import numpy as np

a7 = np.arange(1, 17).reshape(4, 4)

print(a7)
print("Third row:", a7[2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Third row: [ 9 10 11 12]


Q18. Extract the second column.

In [23]:
import numpy as np

a8 = np.arange(1, 17).reshape(4, 4)

print(a8)
print("Second column:")
print(a8[:, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second column:
[ 2  6 10 14]


Q19. Extract the last column.

In [24]:
import numpy as np

a9 = np.arange(1, 17).reshape(4, 4)

print(a9)
print("Last column:")
print(a9[:, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Last column:
[ 4  8 12 16]


Q20. Extract first two rows.

In [25]:
import numpy as np

b1 = np.arange(1, 17).reshape(4, 4)

print(b1)
print("First two rows:")
print(b1[:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First two rows:
[[1 2 3 4]
 [5 6 7 8]]


Q21. Extract last two rows.

In [26]:
import numpy as np

b2 = np.arange(1, 17).reshape(4, 4)

print(b2)
print("Last two rows:")
print(b2[2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Last two rows:
[[ 9 10 11 12]
 [13 14 15 16]]


Q22. Extract first three columns.

In [27]:
import numpy as np

b3 = np.arange(1, 17).reshape(4, 4)

print(b3)
print("First three columns:")
print(b3[:, :3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First three columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


Q23. Extract last two columns.

In [28]:
import numpy as np

b4 = np.arange(1, 17).reshape(4, 4)

print(b4)
print("Last two columns:")
print(b4[:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


Q24. Extract a 2×2 center block.

In [29]:
import numpy as np

b5 = np.arange(1, 17).reshape(4, 4)

print(b5)
print("2×2 center block:")
print(b5[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2×2 center block:
[[ 6  7]
 [10 11]]


Q25. Extract bottom-right 3×3 block.

In [30]:
import numpy as np

b6 = np.arange(1, 17).reshape(4, 4)

print(b6)
print("Bottom-right 3×3 block:")
print(b6[1:, 1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Bottom-right 3×3 block:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


Q26. Extract center element.

In [31]:
import numpy as np

b7 = np.arange(1, 10).reshape(3, 3)

print(b7)
print("Center element:", b7[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Center element: 5


Q27. Extract center 3×3 block.

In [32]:
import numpy as np

b8 = np.arange(1, 26).reshape(5, 5)

print(b8)
print("Center 3×3 block:")
print(b8[1:4, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Center 3×3 block:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Q28. Extract top-right corner block.

In [33]:
import numpy as np

b9 = np.arange(1, 17).reshape(4, 4)

print(b9)
print("Top-right corner block:")
print(b9[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Top-right corner block:
[[3 4]
 [7 8]]


Q29. Extract bottom-left corner block.

In [34]:
import numpy as np

c1 = np.arange(1, 17).reshape(4, 4)

print(c1)
print("Bottom-left corner block:")
print(c1[2:, :2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Bottom-left corner block:
[[ 9 10]
 [13 14]]


Q30. Extract the main diagonal manually using slicing/indexing.

In [35]:
import numpy as np

c2 = np.arange(1, 17).reshape(4, 4)

print(c2)
print("Main diagonal:")
print([c2[0, 0], c2[1, 1], c2[2, 2], c2[3, 3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Main diagonal:
[np.int64(1), np.int64(6), np.int64(11), np.int64(16)]


Q31. Extract every alternate row.

In [36]:
import numpy as np

c3 = np.arange(1, 17).reshape(4, 4)

print(c3)
print("Alternate rows:")
print(c3[::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Alternate rows:
[[ 1  2  3  4]
 [ 9 10 11 12]]


Q32. Extract every alternate column.

In [37]:
import numpy as np

c4 = np.arange(1, 17).reshape(4, 4)

print(c4)
print("Alternate columns:")
print(c4[:, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Alternate columns:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


Q33. Reverse the rows.

In [38]:
import numpy as np

c5 = np.arange(1, 17).reshape(4, 4)

print(c5)
print("Rows reversed:")
print(c5[::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Rows reversed:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Q34. Reverse the columns.

In [39]:
import numpy as np

c6 = np.arange(1, 17).reshape(4, 4)

print(c6)
print("Columns reversed:")
print(c6[:, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Columns reversed:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Q35. Reverse the entire matrix.

In [40]:
import numpy as np

c7 = np.arange(1, 17).reshape(4, 4)

print(c7)
print("Entire matrix reversed:")
print(c7[::-1, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Entire matrix reversed:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Q36. Extract a 3×3 reversed center block.

In [41]:
import numpy as np

c8 = np.arange(1, 26).reshape(5, 5)

print(c8)
print("3×3 reversed center block:")
print(c8[1:4, 1:4][::-1, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
3×3 reversed center block:
[[19 18 17]
 [14 13 12]
 [ 9  8  7]]


Q37. Extract only the corner elements.

In [42]:
import numpy as np

c9 = np.arange(1, 17).reshape(4, 4)

print(c9)
print("Corner elements:")
print([c9[0, 0], c9[0, -1], c9[-1, 0], c9[-1, -1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Corner elements:
[np.int64(1), np.int64(4), np.int64(13), np.int64(16)]


Q38. Extract only the border elements.

In [43]:
import numpy as np

d1 = np.arange(1, 26).reshape(5, 5)

print(d1)

print("Top row:", d1[0])
print("Bottom row:", d1[-1])
print("Left column:", d1[1:-1, 0])
print("Right column:", d1[1:-1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Top row: [1 2 3 4 5]
Bottom row: [21 22 23 24 25]
Left column: [ 6 11 16]
Right column: [10 15 20]


Q39. Increase sales [100,200,300,400] by 10.

In [44]:
import numpy as np

d2 = np.array([100, 200, 300, 400])

d2 = d2 + 10

print(d2)

[110 210 310 410]


Q40. Increase salaries by 15%.

In [45]:
import numpy as np

d3 = np.array([25000, 30000, 35000, 40000])

d3 = d3 * 1.15

print(d3)

[28750. 34500. 40250. 46000.]


Q41. Apply 18% GST to prices.

In [46]:
import numpy as np

d4 = np.array([100, 200, 300, 400])

d4 = d4 * 1.18

print(d4)

[118. 236. 354. 472.]


Q42. Subtract 5 from every element.

In [47]:
import numpy as np

d5 = np.array([10, 20, 30, 40, 50])

d5 = d5 - 5

print(d5)

[ 5 15 25 35 45]


Q43. Find total sales.

In [48]:
import numpy as np

d6 = np.array([100, 200, 300, 400])

print("Total Sales:", np.sum(d6))

Total Sales: 1000


Q44. Find average sales.

In [49]:
import numpy as np

d7 = np.array([100, 200, 300, 400])

print("Average Sales:", np.mean(d7))

Average Sales: 250.0


Q45. Find maximum sales.

In [50]:
import numpy as np

d8 = np.array([100, 200, 300, 400])

print("Maximum Sales:", np.max(d8))

Maximum Sales: 400


Q46. Find minimum sales.

In [51]:
import numpy as np

d9 = np.array([100, 200, 300, 400])

print("Minimum Sales:", np.min(d9))

Minimum Sales: 100


Q47. Find standard deviation.

In [52]:
import numpy as np

e1 = np.array([100, 200, 300, 400])

print("Standard Deviation:", np.std(e1))

Standard Deviation: 111.80339887498948


Q48. Find variance.

In [53]:
import numpy as np

e2 = np.array([100, 200, 300, 400])

print("Variance:", np.var(e2))

Variance: 12500.0


Q49. Find median.

In [54]:
import numpy as np

e3 = np.array([100, 200, 300, 400])

print("Median:", np.median(e3))

Median: 250.0


Q50. Mini Project: Analyze a sales dataset using NumPy.

In [6]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

data.shape

(1000, 10)

In [7]:
data

array([[ 1001,    52,     2, ...,     2, 18737,     2],
       [ 1002,    93,    15, ...,     4, 12728,     2],
       [ 1003,    15,     8, ...,     1, 16726,     2],
       ...,
       [ 1998,    18,    11, ...,     3, 18505,     4],
       [ 1999,   100,     1, ...,     3, 10564,     1],
       [ 2000,    86,     7, ...,     5, 19793,     3]])

Q1. Dataset Exploration

Find:

Shape
Number of Dimensions
Datatype
Total Number of Elements

In [55]:
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Datatype:", data.dtype)
print("Total Elements:", data.size)

Shape: (1000, 10)
Dimensions: 2
Datatype: int64
Total Elements: 10000


Q2. First Look at Data

Display:

First 10 rows

Last 10 rows

In [56]:
print(data[:10])
print(data[-10:])

[[ 1001    52     2  1724     7 30461 12566     2 18737     2]
 [ 1002    93    15  2872    19 13102  2359     4 12728     2]
 [ 1003    15     8  3826    16  9756 10120     1 16726     2]
 [ 1004    72     8  3247     0 21084  1357     5 17481     2]
 [ 1005    61    17  4189    11 47480   564     3 16430     4]
 [ 1006    21    12  4906    25 35181 14162     1 13114     5]
 [ 1007    83    19  2290    18 26292  3394     3 10616     4]
 [ 1008    87    10  1016    14 22404  6874     5 13644     4]
 [ 1009    75     9  4086     8 43861  7531     4 16413     1]
 [ 1010    75     5  2975     6 35040  1330     2 11203     1]]
[[ 1991    17     6  3860     3 22750  2562     5 19344     5]
 [ 1992    13     2  1975     0 19450 13750     5 16985     3]
 [ 1993    84    18  4133    17 17859  9922     2 10947     3]
 [ 1994    25    13  1089     0 24096 13592     2 14760     4]
 [ 1995    68     9  3844    25 26030   387     1 19909     2]
 [ 1996    10    19  2786    25  1762  6053     5 1006

Q3. Using the Sales column:(Sales Column number 5)

Find:

Total Sales

Average Sales

Maximum Sales

Minimum Sales

In [57]:
print("Total Sales:", np.sum(data[:, 5]))
print("Average Sales:", np.mean(data[:, 5]))
print("Maximum Sales:", np.max(data[:, 5]))
print("Minimum Sales:", np.min(data[:, 5]))

Total Sales: 25288432
Average Sales: 25288.432
Maximum Sales: 49930
Minimum Sales: 582


Q4. Using the Profit column:(column number 6)

Find:

Total Profit

Average Profit

Maximum Profit

In [58]:
print("Total Profit:", np.sum(data[:, 6]))
print("Average Profit:", np.mean(data[:, 6]))
print("Maximum Profit:", np.max(data[:, 6]))

Total Profit: 7557939
Average Profit: 7557.939
Maximum Profit: 14984


Q5. Indexing Challenge

Display:

Row 100

Row 500

Row 999

In [59]:
print(data[99])
print(data[499])
print(data[998])

[ 1100    24     5  1562     6 36017  3236     5 15599     4]
[ 1500    67    18  2356    30 36029  4159     1 15580     2]
[ 1999   100     1  1874    19  3827  1261     3 10564     1]


Q6. Slicing Challenge

Display:

Rows 100–200

First 5 columns

Last 3 columns

In [60]:
print(data[99:200])
print(data[:, :5])
print(data[:, -3:])

[[ 1100    24     5 ...     5 15599     4]
 [ 1101    26     5 ...     4 11716     3]
 [ 1102    89    19 ...     1 10786     1]
 ...
 [ 1198    70    14 ...     3 10142     1]
 [ 1199    72     8 ...     4 11410     3]
 [ 1200    27     9 ...     2 10534     5]]
[[1001   52    2 1724    7]
 [1002   93   15 2872   19]
 [1003   15    8 3826   16]
 ...
 [1998   18   11  693   19]
 [1999  100    1 1874   19]
 [2000   86    7 2559   22]]
[[    2 18737     2]
 [    4 12728     2]
 [    1 16726     2]
 ...
 [    3 18505     4]
 [    3 10564     1]
 [    5 19793     3]]


Q7. Advanced Slicing

Display:

Every alternate row

Every alternate column

Dataset in reverse order

In [61]:
print(data[::2])
print(data[:, ::2])
print(data[::-1])

[[ 1001    52     2 ...     2 18737     2]
 [ 1003    15     8 ...     1 16726     2]
 [ 1005    61    17 ...     3 16430     4]
 ...
 [ 1995    68     9 ...     1 19909     2]
 [ 1997    67    13 ...     2 18828     4]
 [ 1999   100     1 ...     3 10564     1]]
[[ 1001     2     7 12566 18737]
 [ 1002    15    19  2359 12728]
 [ 1003     8    16 10120 16726]
 ...
 [ 1998    11    19  2007 18505]
 [ 1999     1    19  1261 10564]
 [ 2000     7    22   229 19793]]
[[ 2000    86     7 ...     5 19793     3]
 [ 1999   100     1 ...     3 10564     1]
 [ 1998    18    11 ...     3 18505     4]
 ...
 [ 1003    15     8 ...     1 16726     2]
 [ 1002    93    15 ...     4 12728     2]
 [ 1001    52     2 ...     2 18737     2]]


Q8. Broadcasting

Management decides to increase all sales by 10%.

Create a new sales array with updated values.

In [63]:
s1 = data[:, 5] * 1.10

print(s1)


[33507.1 14412.2 10731.6 23192.4 52228.  38699.1 28921.2 24644.4 48247.1
 38544.  29739.6 21630.4 14845.6  3708.1 51152.2 25438.6 12123.1 48301.
  1795.2 37363.7 16537.4 26789.4 47847.8 43521.5 50717.7  9143.2  5562.7
  2946.9 48727.8 10521.5  9652.5 53192.7 40092.8 23320.  43960.4 47136.1
 31123.4 32211.3 19247.8 15805.9 49527.5 31517.2 23599.4 35260.5 18869.4
 50078.6 39309.6 52223.6 17096.2 29112.6 53797.7 49295.4 50154.5 16247.
 34548.8 17625.3 52324.8 22540.1 12402.5 14041.5 21954.9 18890.3 30311.6
  7825.4 40172.   8706.5 26020.5 54923.  48822.4 19210.4 42048.6 41298.4
 41848.4 36027.2  4765.2 28352.5 16941.1 42584.3 38112.8 47446.3 25759.8
 51913.4 22044.  13288.  42792.2 42985.8 27958.7 25099.8 11746.9 14026.1
 51038.9 21992.3 23062.6 33776.6 50572.5 22136.4 29770.4 25203.2 31339.
 39618.7 15021.6 25920.4 28832.1 33666.6 18797.9 26659.6 23622.5 40389.8
  8485.4 34189.1 22764.5 49590.2 30389.7  6205.1 32322.4 27923.5  3528.8
 20762.5 17146.8 49612.2 50100.6 11565.4  4150.3 52398

Q9. Business Filtering

Find:

Number of orders where Sales > ₹25,000

Number of orders where Profit > ₹5,000

In [64]:
print(np.sum(data[:, 5] > 25000))
print(np.sum(data[:, 6] > 5000))

509
658


Q10. Management Report

Create a final report showing:

Total Sales

Average Sales

Total Profit

Average Profit

Highest Sale

Highest Profit

Number of High-Value Orders (Sales > ₹25,000)

In [65]:
print("----- Management Report -----")
print("Total Sales:", np.sum(data[:, 5]))
print("Average Sales:", np.mean(data[:, 5]))
print("Total Profit:", np.sum(data[:, 6]))
print("Average Profit:", np.mean(data[:, 6]))
print("Highest Sale:", np.max(data[:, 5]))
print("Highest Profit:", np.max(data[:, 6]))
print("Number of High-Value Orders (Sales > ₹25,000):", np.sum(data[:, 5] > 25000))

----- Management Report -----
Total Sales: 25288432
Average Sales: 25288.432
Total Profit: 7557939
Average Profit: 7557.939
Highest Sale: 49930
Highest Profit: 14984
Number of High-Value Orders (Sales > ₹25,000): 509
